CREATE TABLE DM_TEMPO (
SK_TEMPO          NUMBER,
DT_CALENDARIO     DATE,
NU_DIA            NUMBER,
NU_DIA_SEMANA     NUMBER,
DS_DIA_SEMANA     VARCHAR2(15),
NU_MES            NUMBER,
DS_MES            VARCHAR2(10),
NU_MES_ANO        NUMBER,
DS_MES_ANO        VARCHAR2(8),
NU_BIMESTRE       NUMBER,
DS_BIMESTRE       VARCHAR2(20),
NU_TRIMESTRE      NUMBER,
DS_TRIMESTRE      VARCHAR2(20),
NU_SEMESTRE       NUMBER,
DS_SEMESTRE       VARCHAR2(20),
NU_ANO            NUMBER,
FL_DIA_UTIL       CHAR(2),
FL_FERIADO        CHAR(2)
);
COMMENT ON COLUMN DM_TEMPO.SK_TEMPO           IS 'Chave artificial da dimensão tempo';
COMMENT ON COLUMN DM_TEMPO.DT_CALENDARIO      IS 'Data calendário';
COMMENT ON COLUMN DM_TEMPO.NU_DIA             IS 'Número do dia';
COMMENT ON COLUMN DM_TEMPO.NU_DIA_SEMANA      IS 'Númedo do dia da semana';
COMMENT ON COLUMN DM_TEMPO.DS_DIA_SEMANA      IS 'Descrição do dia da semana';
COMMENT ON COLUMN DM_TEMPO.NU_MES             IS 'Número do mês';
COMMENT ON COLUMN DM_TEMPO.DS_MES             IS 'Descrição do mês';
COMMENT ON COLUMN DM_TEMPO.NU_MES_ANO         IS 'Número do mês e ano';
COMMENT ON COLUMN DM_TEMPO.DS_MES_ANO         IS 'Descrição do mês e ano';
COMMENT ON COLUMN DM_TEMPO.NU_BIMESTRE        IS 'Número do bimestre';
COMMENT ON COLUMN DM_TEMPO.DS_BIMESTRE        IS 'Descrição do bimestre';
COMMENT ON COLUMN DM_TEMPO.NU_TRIMESTRE       IS 'Número do trimestre';
COMMENT ON COLUMN DM_TEMPO.DS_TRIMESTRE       IS 'Descrição do trimestre';
COMMENT ON COLUMN DM_TEMPO.NU_SEMESTRE        IS 'Número do semestre';
COMMENT ON COLUMN DM_TEMPO.DS_SEMESTRE        IS 'Descrição do semestre';
COMMENT ON COLUMN DM_TEMPO.NU_ANO             IS 'Número do ano';
COMMENT ON COLUMN DM_TEMPO.FL_DIA_UTIL        IS 'Flag de dia útil';
COMMENT ON COLUMN DM_TEMPO.FL_FERIADO         IS 'Flag de feriado';

---------------------------------LEMBRETE
-----------------------------------------

-----BLOCO ANÔNIMO PARA CARGA DA DM_TEMPO
-----------------------------------------
DECLARE 
-------------------CONSTANTES DE CONTROLE
V_DATA_INICIO       DATE := '01-01-1900';
V_DATA_FIM          DATE := '31-12-2030';
V_CONTADOR          NUMBER := 0;
-----------------------VARIÁVEIS DE CARGA
-----------------------------------------
V_SK_TEMPO          NUMBER;
V_DATA_CALENDARIO   DATE;
V_NU_DIA            NUMBER;
V_NU_DIA_SEMANA     NUMBER;
V_DS_DIA_SEMANA     VARCHAR2(15);
V_NU_MES            NUMBER;
V_DS_MES            VARCHAR2(10);
V_NU_MES_ANO        NUMBER;
V_DS_MES_ANO        VARCHAR2(8);
V_NU_BIMESTRE       NUMBER;
V_DS_BIMESTRE       VARCHAR2(20);
V_NU_TRIMESTRE      NUMBER;
V_DS_TRIMESTRE      VARCHAR2(20);
V_NU_SEMESTRE       NUMBER;
V_DS_SEMESTRE       VARCHAR2(20);
V_NU_ANO            NUMBER;
V_FL_DIA_UTIL       CHAR(2);
V_FL_FERIADO        CHAR(2) := NULL;

BEGIN
LOOP
V_DATA_CALENDARIO   := V_DATA_INICIO + V_CONTADOR;
V_CONTADOR          := V_CONTADOR + 1;
V_SK_TEMPO          := TO_NUMBER(TO_CHAR(V_DATA_CALENDARIO, 'YYYYMMDD'));
V_NU_DIA            := EXTRACT(DAY FROM V_DATA_CALENDARIO);
V_NU_DIA_SEMANA     := TO_NUMBER(TO_CHAR (V_DATA_CALENDARIO, 'D'));
V_DS_DIA_SEMANA     := TO_CHAR (V_DATA_CALENDARIO, 'DAY');
V_NU_MES            := EXTRACT(MONTH FROM V_DATA_CALENDARIO);
V_DS_MES            := TO_CHAR (V_DATA_CALENDARIO, 'MONTH');
V_NU_MES_ANO        := TO_NUMBER(TO_CHAR (V_DATA_CALENDARIO,'YYYYMM'));
V_DS_MES_ANO        := TO_CHAR(V_DATA_CALENDARIO, 'MON YYYY');
V_NU_ANO            := EXTRACT(YEAR FROM V_DATA_CALENDARIO);

V_NU_BIMESTRE       :=  CASE 
WHEN V_NU_MES IN (1,2)  THEN 1
WHEN V_NU_MES IN (3,4)  THEN 2
WHEN V_NU_MES IN (5,6)  THEN 3
WHEN V_NU_MES IN (7,8)  THEN 4
WHEN V_NU_MES IN (9,10) THEN 5
ELSE 6 END;

V_DS_BIMESTRE :=  CASE 
WHEN V_NU_MES IN (1,2)   THEN '1º BIMESTRE'
WHEN V_NU_MES IN (3,4)   THEN '2º BIMESTRE'
WHEN V_NU_MES IN (5,6)   THEN '3º BIMESTRE'
WHEN V_NU_MES IN (7,8)   THEN '4º BIMESTRE'
WHEN V_NU_MES IN (9,10)  THEN '5º BIMESTRE'
WHEN V_NU_MES IN (11,12) THEN '6º BIMESTRE'
END;

V_NU_TRIMESTRE := CASE
WHEN V_NU_MES IN (1,2,3) THEN 1
WHEN V_NU_MES IN (4,5,6) THEN 2
WHEN V_NU_MES IN (7,8,9) THEN 3
ELSE 4 END;

V_DS_TRIMESTRE := CASE
WHEN V_NU_MES IN (1,2,3)    THEN '1º TRIIMESTRE'
WHEN V_NU_MES IN (4,5,6)    THEN '2º TRIIMESTRE'
WHEN V_NU_MES IN (7,8,9)    THEN '3º TRIIMESTRE'
WHEN V_NU_MES IN (10,11,12) THEN '4º TRIIMESTRE'
END;

IF V_NU_MES < 7
THEN V_NU_SEMESTRE := 1;
ELSE V_NU_SEMESTRE := 2;
END IF;

IF V_NU_MES < 7
THEN V_DS_SEMESTRE := '1º SEMESTRE';
ELSE V_DS_SEMESTRE := '2º SEMESTRE';
END IF;

IF V_NU_DIA_SEMANA IN (1, 7)
THEN V_FL_DIA_UTIL := 'N';
ELSE V_FL_DIA_UTIL := 'S';
END IF;

INSERT INTO DM_TEMPO VALUES (
V_SK_TEMPO          ,
V_DATA_CALENDARIO   ,
V_NU_DIA            ,
V_NU_DIA_SEMANA     ,
V_DS_DIA_SEMANA     ,
V_NU_MES            ,
V_DS_MES            ,
V_NU_MES_ANO        ,
V_DS_MES_ANO        ,
V_NU_BIMESTRE       ,
V_DS_BIMESTRE       ,
V_NU_TRIMESTRE      ,
V_DS_TRIMESTRE      ,
V_NU_SEMESTRE       ,
V_DS_SEMESTRE       ,
V_NU_ANO            ,
V_FL_DIA_UTIL       ,
V_FL_FERIADO        );
EXIT WHEN V_DATA_CALENDARIO = V_DATA_FIM;
COMMIT;
END LOOP;
END ;
